Synergia.B2B.Web/Models/HoodFinalOfferDetailsViewModel.cs
using Synergia.B2B.Common.Dto.Web.Offer;
using Synergia.B2B.Common.Entities;
using Synergia.B2B.Common.Enums;
using Synergia.B2B.Common.Extensions;
using Synergia.B2B.Common.Helpers;
using Synergia.B2B.Repository.Helpers;
using Synergia.B2B.Repository.Repositories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Synergia.B2B.Web.Models
{
    public class HoodFinalOfferDetailsViewModel
    {
        public int? HFOOfferId { get; set; }
        public List<InstallationObjectItemDto> OfferInstallationObjectDataItems { get; set; }
        public List<SelectListItem> InstallationObjectTypes { get; set; }
        public List<SelectListItem> Groups { get; set; }
        public List<SelectListItem> Statuses { get; set; }
        public List<SelectListItem> PaymentTypes { get; set; }
        public List<SelectListItem> Regions { get; set; }


        [Display(Name = "Logo")]
        public string HFOLogo { get; set; }

        [Required]
        [Display(Name = "Numer oferty")]
        public string HFOOfferNumber { get; set; }

        [Required]
        public decimal HFOCatalogValueNet { get; set; }

        [Required]
        public decimal HFOCatalogValueVat { get; set; }

        [Required]
        public decimal HFOCatalogValueGross { get; set; }

        [Required]
        public decimal HFOFinalValueAfterAllDiscountsNet { get; set; }

        [Required]
        public decimal HFOFinalValueAfterAllDiscountsVat { get; set; }

        [Required]
        public decimal HFOFinalValueAfterAllDiscountsGross { get; set; }

        [Display(Name = "Data")]
        public DateTime? HFOOfferDate { get; set; }

        [Display(Name = "Miasto")]
        public string HFOCity { get; set; }

        [Display(Name = "Nabywca")]
        public string HFOOfferCompanyName { get; set; }

        public int? HFOOfferCompanyId { get; set; }

        [Display(Name = "Miasto nabywcy")]
        public string HFOOfferCompanyCity { get; set; }

        [Display(Name = "Kod nabywcy")]
        public string HFOOfferCompanyPostalCode { get; set; }

        [Display(Name = "Adres nabywcy")]
        public string HFOOfferCompanyAddress { get; set; }

        [Display(Name = "NIP nabywcy")]
        public string HFOOfferCompanyNIP { get; set; }

        [Display(Name = "Nazwa")]
        public string HFOInstallationObjectName { get; set; }

        public int? HFOInstallationObjectId { get; set; }

        [Display(Name = "Miasto obiektu")]
        public string HFOInstallationObjectCity { get; set; }

        [Display(Name = "Kod obiektu")]
        public string HFOInstallationObjectPostalCode { get; set; }

        [Display(Name = "Adres obiektu")]
        public string HFOInstallationObjectAddress { get; set; }

        [Display(Name = "Kraj obiektu")]
        public string HFOInstallationObjectCountry { get; set; }

        [Display(Name = "Typ obiektu")]
        public string HFOInstallationObjectType { get; set; }

        [Display(Name = "Status")]
        public string HFOStatusText { get; set; }
        public byte HFOStatus { get; set; }

        [Display(Name = "Płatność")]
        public OfferPaymentType HFOPaymentType { get; set; }

        [Display(Name = "Czas realizacji")]
        public string HFODeliveryTime { get; set; }

        [Display(Name = "Okapy")]
        public byte HFOGuaranteeYearsHoods { get; set; }

        [Display(Name = "Nawiewniki")]
        public byte HFOGuaranteeYearsVentilators { get; set; }

        [Display(Name = "CookAir")]
        public byte HFOGuaranteeYearsCookAir { get; set; }

        [Display(Name = "Smoki")]
        public byte HFOGuaranteeYearsSmoki { get; set; }

        [Display(Name = "Ansul")]
        public byte HFOGuaranteeYearsAnsul { get; set; }

        [Display(Name = "KES")]
        public byte HFOGuaranteeYearsKES { get; set; }

        [Display(Name = "Region")]
        public int HFORegionId { get; set; }

        [Display(Name = "Zadatek (%)")]
        public byte HFOPrepaymentPercent { get; set; }
        
        [Display(Name = "Rabat (%)")]
        public decimal HFODiscount { get; set; }

        [Display(Name = "Zapytanie osoba")]
        public string HFOContactPerson { get; set; }

        [EmailAddress]
        [Display(Name = "Zapytanie adres e-mail")]
        public string HFOContactEmail { get; set; }

        [Display(Name = "Zapytanie telefon")]
        public string HFOContactPhone { get; set; }

        [Display(Name = "Uwagi")]
        public string HFOComment { get; set; }

        [Display(Name = "Ukryj rabaty na dokumencie oferty")]
        public bool HFOHideDiscountInPdfFile { get; set; }

        [Display(Name = "Stała wartość netto (zł)")]
        public decimal? HFOFixedValueAfterAllDiscounts { get; set; }

        #region Constructor
        public HoodFinalOfferDetailsViewModel()
        {
            if (HttpContext.Current.Session != null)
            {
                OfferCompanyRepository offerCompanyRepository = new OfferCompanyRepository();
                List<OfferCompany> offerCompanies = null;
                if (HttpContext.Current.User.IsInRole(UserRoleType.Admin.ToString()))
                {
                    offerCompanies = offerCompanyRepository.GetAll();
                }
                else
                {
                    offerCompanies = offerCompanyRepository.GetByOwner(SessionHelper.LoggedUser.Id).ToList();
                }

                InstallationObjectRepository installationObjectRepository = new InstallationObjectRepository();
                List<InstallationObject> installationObjects = null;

                if (HttpContext.Current.User.IsInRole(UserRoleType.Admin.ToString()))
                {
                    installationObjects = installationObjectRepository.GetAll();
                }
                else
                {
                    installationObjects = installationObjectRepository.GetByOwner(SessionHelper.LoggedUser.Id).ToList();
                }

                OfferInstallationObjectDataItems = installationObjects.Select(o => new InstallationObjectItemDto()
                {
                    Name = o.Name,
                    Id = o.Id,
                    OfferCompanyId = o.OfferCompanyId
                }).ToList();

                InstallationObjectTypes = new List<SelectListItem>();
                InstallationObjectTypes.Add(new SelectListItem
                {
                    Text = Resources.Common.InstallationObjectType_Gastronomy,
                    Value = "Gastronomia",
                });
                InstallationObjectTypes.Add(new SelectListItem
                {
                    Text = Resources.Common.InstallationObjectType_Other,
                    Value = "Inne",
                });

                Groups = new List<SelectListItem>();
                GroupRepository groupRepository = new GroupRepository();
                List<Group> groups = groupRepository.GetByParId(2200);
                Groups = groups.Select(c => new SelectListItem()
                {
                    Text = c.Code,
                    Value = c.Id.ToString()
                }).ToList();
                Groups.Insert(Groups.Count, new SelectListItem() { Text = "PRODUKTY WŁASNE", Value = "0" });

                Statuses = new List<SelectListItem>();
                List<OfferStatus> statuses = EnumHelper.EnumToListOrdered<OfferStatus>();
                foreach (var statusItem in statuses)
                {
                    Statuses.Add(new SelectListItem()
                    {
                        Text = statusItem.GetDescription(),
                        Value = statusItem.GetValue()
                    });
                }

                PaymentTypes = EnumHelper.EnumToList<OfferPaymentType>()
                    .Select(pt => new SelectListItem()
                    {
                        Text = pt.GetDescription().Replace(" (Rabat 2%)", ""),
                        Value = pt.GetValue(),
                    })
                    .ToList();

                List<Region> regions = new RegionRepository().GetAll()
                    .OrderBy(x => x.Code)
                    .ToList();

                Regions = regions.Select(o => new SelectListItem()
                {
                    Text = o.Code,
                    Value = o.Id.ToString()
                }).ToList();
            }
        }
        #endregion
    }
}

Synergia.B2B.Web/Models/HoodSelectionOfferDetailsAirCalculationViewModel.cs
//using Synergia.B2B.Common.Entities;
//using Synergia.B2B.Repository.Helpers;
//using Synergia.B2B.Repository.Repositories;
//using Newtonsoft.Json;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;

//namespace Synergia.B2B.Web.Models
//{
//    public class HoodSelectionOfferDetailsAirCalculationViewModel
//    {
//        public List<HoodOfferAirCalculationDevice> DeviceList { get; set; } 

//        public List<SelectListItem> DeviceListSelectListItem
//        {
//            get
//            {
//                return DeviceList.Select(x => new SelectListItem()
//                {
//                    Text = x.Name,
//                    Value = x.Id.ToString()
//                }).ToList();
//            }
//        }

//        public string DeviceListJson
//        {
//            get
//            {
//                return JsonConvert.SerializeObject(DeviceList);
//            }
//        }

//        public HoodSelectionOfferDetailsAirCalculationViewModel()
//        {
//            if(HttpContext.Current.Session != null)
//            {
//                DeviceList = new HoodOfferAirCalculationDeviceRepository().GetAll().OrderBy(x => x.Id).ToList();
//            }
//        }
//    }
//}

Synergia.B2B.Web/Models/HoodSelectionOfferDetailsHoodListViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Synergia.B2B.Web.Models
{
    public class HoodSelectionOfferDetailsHoodListViewModel
    {
        [Display(Name = "")]
        public string AdditionalAccessorySmokiType { get; set; }

        [Display(Name = "")]
        public string AdditionalAccessoryNawiewnikiType { get; set; }

        public List<SelectListItem> AdditionalAccessorySmokiTypeList { get; set; }
        public List<SelectListItem> AdditionalAccessoryNawiewnikiTypeList { get; set; }

        public HoodSelectionOfferDetailsHoodListViewModel()
        {
            AdditionalAccessorySmokiTypeList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text = "SMOKI MAXI GRILL 250"},
                new SelectListItem(){ Text = "SMOKI MAXI GRILL 350"},
                new SelectListItem(){ Text = "SMOKI MAXI GRILL 400"},
                new SelectListItem(){ Text = "SMOKI MAXI GRILL 500"},
                new SelectListItem(){ Text = "SMOKI JUNIOR 200"},
                new SelectListItem(){ Text = "SMOKI JUNIOR 250"},
                new SelectListItem(){ Text = "SMOKI JUNIOR 300"}
            };

            AdditionalAccessoryNawiewnikiTypeList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text = "JRS-300x600"},
                new SelectListItem(){ Text = "JRS-300x1200"},
                new SelectListItem(){ Text = "JRS-600x600"},
                new SelectListItem(){ Text = "JRS-600x900"},
                new SelectListItem(){ Text = "JRS-600x1200"},
                new SelectListItem(){ Text = "JRS-600x1800"},
            };
        }
    }
}

Synergia.B2B.Web/Models/HoodSelectionOfferDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Synergia.B2B.Web.Models
{
    public class HoodSelectionOfferDetailsViewModel
    {
        public int? HoodOfferId { get; set; }

        [Required]
        [RegularExpression("(JE\\d\\d-\\d{1,}_\\d{1,})|(-)")]
        [Display(Name = "Numer oferty")]
        public string HoodOfferNumber { get; set; }

        [Display(Name = "Status")]
        public string HoodStatusText { get; set; }
    }
}

Synergia.B2B.Web/Models/HoodSelectionOfferListViewModel.cs
using Synergia.B2B.Common.Enums;
using Synergia.B2B.Common.Extensions;
using Synergia.B2B.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Synergia.B2B.Web.Models
{
    public class HoodSelectionOfferListViewModel
    {
        public List<SelectListItem> Statuses { get; set; } = new List<SelectListItem>();

        public HoodSelectionOfferListViewModel()
        {
            List<HoodOfferStatus> statuses = EnumHelper.EnumToListOrdered<HoodOfferStatus>();
            statuses.Remove(HoodOfferStatus.New);

            foreach (var statusItem in statuses)
            {
                Statuses.Add(new SelectListItem()
                {
                    Text = statusItem.GetDescription(),
                    Value = statusItem.GetValue()
                });
            }
        }
    }
}

Synergia.B2B.Web/Controllers/HoodSelectionController.cs
using Synergia.B2B.Common.Enums;
using Synergia.B2B.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Synergia.B2B.Web.Controllers
{
    [Authorize(Roles = "Admin, HoodSelection, HoodOffersAndOrders")]
    public class HoodSelectionController : Controller
    {
        [HttpGet]
        public ActionResult HoodSelectionOfferList()
        {
            return View(new HoodSelectionOfferListViewModel());
        }

        [HttpGet]
        public ActionResult HoodSelectionFinishedOfferList()
        {
            return View("HoodSelectionFinishedOfferList", new HoodSelectionOfferListViewModel());
        }

        [HttpGet]
        public ActionResult HoodSelectionFinalOfferList()
        {
            return View("HoodFinalOffersList", new HoodFinalOfferListViewModel());
        }

        [HttpGet]
        public ActionResult HoodSelectionHoodOrderList()
        {
            return View("HoodOrdersList", new HoodOrderListFilterViewModel());
        }

        [HttpGet]
        public ActionResult HoodSelectionOfferDetails(int id)
        {
            return View(new HoodSelectionOfferDetailsViewModel() { HoodOfferId = id });
        }

        [HttpGet]
        public ActionResult HoodsList()
        {
            return View("HoodSelectionAllOfferDetailsHoodList", new HoodSelectionOfferDetailsViewModel());
        }

        [HttpGet]
        public ActionResult HoodPartsPriceList()
        {
            return View();
        }
    }
}

Synergia.B2B.Web/Views/HoodSelection/HoodFinalOffersList.cshtml
@model HoodFinalOfferListViewModel
@Scripts.Render("~/bundles/hoodSelection/HoodFinalOfferList")

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header card-header-text" data-background-color="blueSynergia">
                <h4 class="card-title">Lista ofert okapów</h4>
            </div>
            <div class="card-content">
                <div class="toolbar">
                    <div class="row">
                        <div class="col-md-8"></div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.DropDownList("HoodFinalOfferStatusFilter", Model.Statuses, "Wszystkie oferty", new { @class = "selectpicker", data_style = "select-with-transition" })
                            </div>
                        </div>
                        @*<div class="col-md-2" style="padding-bottom:10px;">
                            <button type="button" class="btn btn-info" data-toggle="modal" id="buttonAddOffer">Dodaj ofertę</button>
                        </div>*@
                    </div>
                </div>

                <div class="material-datatables">
                    <table id="hoodFinalOfferListTable" class="table table-striped table-no-bordered table-hover dataTable" 
                           cellspacing="0" style="width:100%; display:none">
                        <thead>
                            <tr>
                                <th>Nr oferty</th>
                                <th>Data</th>
                                <th>Klient</th>
                                <th>Obiekt</th>
                                <th>Region</th>
                                <th>Wartość katalogowa</th>
                                <th>Wartość po rabacie</th>
                                <th>Wartość końcowa</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_HoodFinalOfferDetails", new HoodFinalOfferDetailsViewModel())

Synergia.B2B.Web/Views/HoodSelection/HoodOrdersList.cshtml
@model HoodOrderListFilterViewModel
@Scripts.Render("~/bundles/hoodSelection/hoodOrdersList")

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header card-header-text" data-background-color="blueSynergia">
                <h4 class="card-title">Lista zamówień okapów</h4>
            </div>
            <div class="card-content">
                <div class="toolbar">
                    <div class="row">
                        <div class="col-sm-offset-9 col-sm-3">
                            <div class="form-group">
                                @Html.DropDownList("HoodOrderTypeFilter", Model.OrderTypes, "Wszystkie zamówienia", new { @class = "selectpicker", data_style = "select-with-transition" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="material-datatables">
                    <table id="hoodOrderstable" class="table table-striped table-no-bordered table-hover dataTable" cellspacing="0" style="width:100%; display:none">
                        <thead>
                            <tr>
                                <th>Nr zam.</th>
                                <th>Data</th>
                                <th>Klient</th>
                                <th>Obiekt</th>
                                <th>Region</th>
                                <th>Wartość katalogowa</th>
                                <th>Wartość końcowa</th>
                                <th>Z oferty nr</th>
                                <th>Status</th>
                                <th>Ilość modułów</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Synergia.B2B.Web/Views/HoodSelection/HoodPartsPriceList.cshtml
@using Synergia.B2B.Web.Models
@model HoodSelectionHoodPartsPriceListViewModel
@Scripts.Render("~/bundles/hoodSelection/hoodSelectionHoodPartsPriceList")
@{ViewBag.Title = "Cennik elementów do okapów";}
<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header card-header-text" data-background-color="blueSynergia">
                <h4 class="card-title">Cennik elementów</h4>
            </div>
            <div class="card-content">
                <div class="toolbar">
                    <div class="row">
                        @*<div class="col-md-8"></div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    @Html.DropDownList("OfferStatusFilter", Model.Statuses, "Wszystkie oferty", new { @class = "selectpicker", data_style = "select-with-transition" })
                                </div>
                            </div>*@
                        @*<div class="col-md-2 col-md-offset-10" style="padding-bottom:10px;">
                                <a data-toggle="modal" data-target="#modalHoodPartsPriceList" class="btn btn-info">Dodaj element</a>
                            </div>*@
                    </div>
                </div>

                <div class="material-datatables">
                    <table id="hoodPartsPriceListTable" class="table table-striped table-no-bordered table-hover dataTable" cellspacing="0" style="width:100%; display:none">
                        <thead>
                            <tr>
                                <th>Nazwa elementu</th>
                                <th>Cena netto</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalAddHoodPartsPriceList" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        @using (Html.BeginForm("AddHoodPartsPriceList", "HoodSelection", FormMethod.Post, new { id = "formAddAddHoodPartsPriceList" }))
        {

            <!-- Modal content-->
            <div class="modal-content">

                @*<div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <i class="material-icons">clear</i>
                        </button>
                        <h4 class="modal-title">&nbsp;</h4>
                    </div>*@
                <div class="modal-body">

                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="rose">
                            <i class="material-icons">perm_identity</i>
                        </div>
                        <div class="card-content">
                            <h4 class="card-title">
                                Cena elementu
                            </h4>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", disabled = "true" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.PriceNet, new { @class = "required control-label" })
                                        @Html.TextBoxFor(model => model.PriceNet, new { @class = "form-control" })
                                    </div>
                                </div>
                                @Html.HiddenFor(m => m.Id)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    <button type="button" onclick="hoodSelectionHoodPartsPriceList.save();" class="btn btn-success">Zapisz cenę</button>
                </div>
            </div>
        }
    </div>
</div>

Synergia.B2B.Web/Views/HoodSelection/_HoodSelectionOfferDetailsForm.cshtml
@model HoodSelectionOfferDetailsFormViewModel
@Scripts.Render("~/bundles/hoodSelection/_HoodSelectionOfferDetailsForm")

<form id="formSaveHoodOfferDetails">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.HoodOfferContactPerson, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.HoodOfferContactPerson, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.HoodOfferContactEmail, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.HoodOfferContactEmail, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.HoodOfferContactPhone, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.HoodOfferContactPhone, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.HoodOfferRegionId, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.HoodOfferRegionId, Model.Regions, "Wybierz region", new { @class = "selectpicker", data_style = "select-with-transition" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.LanguageId, new { @class = "control-label", style = "color: #ff9800; font-weight: bold", })
                @Html.DropDownListFor(model => model.LanguageId, Model.Languages, new { @class = "selectpicker", data_style = "select-with-transition" })
            </div>
        </div>
    </div>
    <div class="panel panel-success" style="margin-top:20px">
        <div class="panel-heading">Dane obiektu</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group label-floating">
                        <div class="checkbox">
                            <label>
                                @Html.CheckBoxAwesome("ChBHoodAddNewInstallationObject", new { @class = "control-label" })
                                @Html.Label("Dodaj obiekt", new { @for = "ChBHoodAddNewInstallationObject" })
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-md-4" id="ColHoodInstallationObjectsDropDown">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectName, new { @class = "control-label" })

                        <input id="HoodOfferSearchObject" class="form-control autocompleteSearch">
                        <button type="button" class="btn btn-white btn-round btn-just-icon btn-round-small" id="btnClearSearchObject">
                            <i class="material-icons">clear</i>
                            <div class="ripple-container"></div>
                        </button>
                        @Html.HiddenFor(model => model.HoodInstallationObjectId)
                        @Html.Hidden("HoodInstallationObjectTempName")
                    </div>
                </div>
                <div class="col-md-4 hidden" id="ColHoodInstallationObjectName">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectName, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.HoodInstallationObjectName, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectAddress, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.HoodInstallationObjectAddress, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-md-offset-2">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectCity, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.HoodInstallationObjectCity, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectPostalCode, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.HoodInstallationObjectPostalCode, new { @class = "form-control", data_mask = "99-999" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectCountry, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.HoodInstallationObjectCountry, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-md-offset-2">
                    <div class="form-group label-floating">
                        @Html.LabelFor(model => model.HoodInstallationObjectType, new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.HoodInstallationObjectType, Model.InstallationObjectTypes, "Wybierz typ obiektu", new { @class = "selectpicker", data_style = "select-with-transition" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group label-static">
                @Html.LabelFor(model => model.Comment, new { @class = "control-label"})
                @Html.TextAreaFor(x => x.Comment, new { @class = "form-control", rows = "2" })
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-md-12 text-right">
        <button type="button" id="btnFinishHoodOffer" class="btn btn-warning hidden" style="width:150px; margin-right: 50px">Zakończ</button>
        <button type="button" id="btnOfferHoodOffer" class="btn btn-danger hidden" style="width:150px; margin-right: 50px">Zaofertuj</button>
        <a href="@Url.Action("HoodSelectionOfferList", "HoodSelection")" class="btn btn-default">Cofnij do listy ofert</a>
        <button type="button" class="btn btn-success" id="btnSaveHoodOffer">Zapisz</button>
    </div>
</div>